name: Lint and Build Code Base

on:
  push:
    branches: [dev, main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, dev, release-*]
  workflow_dispatch:

jobs:
  lint-server:
    name: Lint Server Code Base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
          cache-dependency-path: ./server/package-lock.json
            
      - name: Install Dependencies - server
        run: npm ci
        working-directory: ./server

      - name: Lint - server
        run: npm run lint
        working-directory: ./server
      - name: Prettier - server
        run: npm run prettier
        working-directory: ./server
      - name: All went well!
        run: echo Success
    env:
      CI: true
  
  build-server:
    name: Build Server Code Base
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [lint-server]
    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
          cache-dependency-path: ./server/package-lock.json
            
      - name: Install Dependencies - server
        run: npm ci
        working-directory: ./server
      - name: Build Dependencies - server
        run: npm ci
        working-directory: ./server
        env:
          NODE_ENV: production

  lint-client:
    name: Lint Client Code Base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
          cache-dependency-path: ./client/package-lock.json
            
      - name: Install Dependencies - client
        run: npm ci
        working-directory: ./client

      - name: Lint - client
        run: npm run lint
        working-directory: ./client
    env:
      CI: true

  build-client:
    name: Build Client Code Base
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [lint-client]
    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
          cache-dependency-path: ./client/package-lock.json
            
      - name: Install Dependencies - client
        run: npm ci
        working-directory: ./client
      - name: Build Dependencies - client
        run: npm ci
        working-directory: ./client
        env:
          NODE_ENV: production
